// Khazana King OTT - Catalog Database

window.movieData = [
  // ==================== MOVIES (m1 to m20) ====================
  {
    id: "m1",
    title: "Sintel: Quest for the Dragon",
    type: "movie",
    description: "A lonely young woman named Sintel rescues a baby dragon she names Scales. When Scales is kidnapped by an adult dragon, Sintel embarks on a treacherous quest to rescue her companion.",
    rating: "8.9",
    year: 2025,
    genres: ["Action", "Drama", "Thriller"],
    language: "English",
    country: "Netherlands",
    duration: "15m 48s",
    banner: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    cast: ["Sintel", "Scales", "The Shaman"],
    trending: true,
    popular: true,
    topRated: true,
    recommended: true,
    isLatest: true,
    tagline: "A bond forged in fire. A search without limits."
  },
  {
    id: "m2",
    title: "Tears of Steel: The Cybernetic Age",
    type: "movie",
    description: "Set in a dystopian future Amsterdam, a group of scientists and soldiers attempt to salvage a broken relationship to prevent giant robotic spiders from destroying the planet.",
    rating: "8.7",
    year: 2024,
    genres: ["Action", "Thriller", "Horror"],
    language: "English",
    country: "USA",
    duration: "12m 14s",
    banner: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    cast: ["Celia", "Barak", "Zhang"],
    trending: true,
    popular: true,
    topRated: false,
    recommended: true,
    isLatest: false,
    tagline: "The cost of technology is written in steel."
  },
  {
    id: "m3",
    title: "Big Buck Bunny: Return to the Forest",
    type: "movie",
    description: "When three mischievous rodents bully a giant, friendly rabbit, he decides to orchestrate an elaborate series of traps to teach them a lesson they will never forget.",
    rating: "9.2",
    year: 2026,
    genres: ["Comedy", "Kids", "Action"],
    language: "Hindi",
    country: "India",
    duration: "9m 56s",
    banner: "https://images.unsplash.com/photo-1500485035595-cbe6f645feb1?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    cast: ["Bunny", "Frank the Squirrel", "Rinky"],
    trending: true,
    popular: false,
    topRated: true,
    recommended: true,
    isLatest: true,
    tagline: "Don't mess with the big bunny."
  },
  {
    id: "m4",
    title: "Elephants Dream: Mechanical Utopia",
    type: "movie",
    description: "Two characters, Proog and Emo, wander through an infinitely complex mechanical universe that behaves like a living being, exposing the rift between reality and perception.",
    rating: "8.5",
    year: 2023,
    genres: ["Drama", "Romance", "Documentary"],
    language: "English",
    country: "UK",
    duration: "10m 54s",
    banner: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    cast: ["Proog", "Emo"],
    trending: false,
    popular: true,
    topRated: true,
    recommended: false,
    isLatest: false,
    tagline: "Dreams are built in gears."
  },
  {
    id: "m5",
    title: "The Escape Project",
    type: "movie",
    description: "An elite operative is sent into a high-security lockup to extract an asset, only to find the entire prison has been taken over by a rogue synthetic intelligence.",
    rating: "8.3",
    year: 2026,
    genres: ["Action", "Thriller"],
    language: "Hindi",
    country: "India",
    duration: "15m 12s",
    banner: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    cast: ["Kabir Malhotra", "Diana D'Souza", "Samrat Sengupta"],
    trending: true,
    popular: true,
    topRated: false,
    recommended: true,
    isLatest: true,
    tagline: "No walls can contain the truth."
  },
  {
    id: "m6",
    title: "Blaze of Glory",
    type: "movie",
    description: "A firefighter fighting a massive forest blaze stumbles upon a hidden container containing high-tech espionage components, making him the target of international mercenaries.",
    rating: "8.1",
    year: 2025,
    genres: ["Action", "Drama"],
    language: "English",
    country: "USA",
    duration: "15m 02s",
    banner: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    cast: ["Tom Mitchell", "Sarah Connor"],
    trending: true,
    popular: false,
    topRated: true,
    recommended: true,
    isLatest: true,
    tagline: "Fire burns hot, but betrayal burns deeper."
  },
  {
    id: "m7",
    title: "Fun in the Sun",
    type: "movie",
    description: "A lighthearted comedy about a group of childhood friends who reunite at a beach house only to find themselves accidentally holding a suitcase belonging to the local mafia.",
    rating: "8.0",
    year: 2025,
    genres: ["Comedy", "Romance"],
    language: "English",
    country: "USA",
    duration: "14m 58s",
    banner: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    cast: ["Ryan Reynolds", "Emma Stone"],
    trending: false,
    popular: true,
    topRated: false,
    recommended: true,
    isLatest: true,
    tagline: "Sun, sand, and accidental crime."
  },
  {
    id: "m8",
    title: "Joyride Chronicles",
    type: "movie",
    description: "Two teenage siblings take their father's classic car for a spin, unaware that the trunk contains an experimental energy core that local government agents are desperately hunting.",
    rating: "8.2",
    year: 2024,
    genres: ["Action", "Kids", "Comedy"],
    language: "Hindi",
    country: "India",
    duration: "15m 05s",
    banner: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    cast: ["Rohan Roy", "Ananya Sen"],
    trending: true,
    popular: true,
    topRated: false,
    recommended: false,
    isLatest: false,
    tagline: "The ride of their lives. Literally."
  },
  {
    id: "m9",
    title: "Meltdown Protocol",
    type: "movie",
    description: "When a nuclear reactor's AI system locks out the human operators and initiates a countdown sequence, a disgraced technician is the only one who can enter the core and shut it down.",
    rating: "7.9",
    year: 2024,
    genres: ["Thriller", "Action"],
    language: "English",
    country: "UK",
    duration: "15m 01s",
    banner: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
    cast: ["Idris Elba", "Rebecca Ferguson"],
    trending: false,
    popular: true,
    topRated: true,
    recommended: true,
    isLatest: false,
    tagline: "Seconds count. Degrees kill."
  },
  {
    id: "m10",
    title: "Bullrun: Redline Highway",
    type: "movie",
    description: "An underground cross-country racing tournament becomes a deadly trap when a ruthless tech billionaire hacks all contestants' GPS trackers, forcing them to finish the race or die.",
    rating: "8.4",
    year: 2026,
    genres: ["Action", "Thriller"],
    language: "English",
    country: "USA",
    duration: "14m 56s",
    banner: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
    cast: ["Dominic Cruz", "Michelle Rodriguez"],
    trending: true,
    popular: true,
    topRated: true,
    recommended: true,
    isLatest: true,
    tagline: "No rules. No limits. No brakes."
  },
  {
    id: "m11",
    title: "Outback Adventure",
    type: "movie",
    description: "An environmentalist and a rugged safari guide embark on a dangerous trek across the Australian outback to locate a rare biological species before corporate poachers do.",
    rating: "8.0",
    year: 2025,
    genres: ["Documentary", "Action"],
    language: "English",
    country: "Australia",
    duration: "14m 45s",
    banner: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
    cast: ["Liam Hemsworth", "Margot Robbie"],
    trending: false,
    popular: true,
    topRated: false,
    recommended: true,
    isLatest: true,
    tagline: "Nature has its own laws."
  },
  {
    id: "m12",
    title: "The 3K Gamble",
    type: "movie",
    description: "Three college students pool together their last $3000 to buy a used vintage car, unaware that a hidden treasure map leading to millions is sewn inside the driver's seat.",
    rating: "8.5",
    year: 2025,
    genres: ["Comedy", "Drama"],
    language: "English",
    country: "UK",
    duration: "14m 32s",
    banner: "https://images.unsplash.com/photo-1514306191717-452ec28c7814?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetFor3G.mp4",
    cast: ["David Tennant", "Michael Sheen"],
    trending: true,
    popular: true,
    topRated: true,
    recommended: false,
    isLatest: true,
    tagline: "One bad car. One great adventure."
  },
  {
    id: "m13",
    title: "Shadow Warrior: Reborn",
    type: "movie",
    description: "A ninja assassin seeks redemption by protecting a young orphan girl who holds the secret key to unlocking an ancient temple of unlimited spiritual power.",
    rating: "8.3",
    year: 2025,
    genres: ["Action", "Thriller"],
    language: "Hindi",
    country: "India",
    duration: "15m 48s",
    banner: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    cast: ["Vidyut Jammwal", "Mrunal Thakur"],
    trending: true,
    popular: false,
    topRated: false,
    recommended: true,
    isLatest: false,
    tagline: "Honour is not given. It is fought for."
  },
  {
    id: "m14",
    title: "Cyberpunk: The Neo-Amsterdam canals",
    type: "movie",
    description: "In a neon-drenched future where cybernetic augmentations are the norm, a detective hunts down an illegal group modifying memory cores to replace civilian minds.",
    rating: "8.6",
    year: 2024,
    genres: ["Action", "Thriller", "Horror"],
    language: "English",
    country: "USA",
    duration: "12m 14s",
    banner: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    cast: ["Keanu Reeves", "Ana de Armas"],
    trending: false,
    popular: true,
    topRated: true,
    recommended: true,
    isLatest: false,
    tagline: "In a world of machines, humanity is the virus."
  },
  {
    id: "m15",
    title: "Forest Bully teaches a lesson",
    type: "movie",
    description: "An animated story of a giant, cute bunny whose peaceful morning routine is constantly interrupted by three mischievous bullies throwing rocks at his butterfly collection.",
    rating: "8.8",
    year: 2026,
    genres: ["Comedy", "Kids"],
    language: "Hindi",
    country: "India",
    duration: "9m 56s",
    banner: "https://images.unsplash.com/photo-1500485035595-cbe6f645feb1?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    cast: ["Animated Bunny", "Forest Animals"],
    trending: true,
    popular: true,
    topRated: true,
    recommended: true,
    isLatest: true,
    tagline: "He's big, he's bunny, and he's not happy."
  },
  {
    id: "m16",
    title: "Gears and Reality",
    type: "movie",
    description: "A profound drama exploring a parallel reality where humans are constructed out of intricate copper gears and clockwork mechanisms, living in fear of the cosmic clock winder.",
    rating: "8.2",
    year: 2023,
    genres: ["Drama", "Romance"],
    language: "English",
    country: "UK",
    duration: "10m 54s",
    banner: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    cast: ["Proog Smith", "Emo Watson"],
    trending: false,
    popular: false,
    topRated: true,
    recommended: false,
    isLatest: false,
    tagline: "What if your soul was wound up?"
  },
  {
    id: "m17",
    title: "Canal Chase in Amsterdam",
    type: "movie",
    description: "A police inspector is framed for corruption and has to speed through the winding canals of Amsterdam using a stolen racing boat to clear his name.",
    rating: "8.1",
    year: 2024,
    genres: ["Action", "Thriller"],
    language: "English",
    country: "Netherlands",
    duration: "12m 14s",
    banner: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    cast: ["Liam Neeson", "Cillian Murphy"],
    trending: true,
    popular: false,
    topRated: false,
    recommended: true,
    isLatest: false,
    tagline: "Water. Speed. Survival."
  },
  {
    id: "m18",
    title: "Underground Racing Circuit",
    type: "movie",
    description: "An high-stakes underground racing tournament in the desert challenges the speed limits of experimental muscle cars, attracting the attention of corrupt authorities.",
    rating: "8.3",
    year: 2026,
    genres: ["Action", "Thriller"],
    language: "English",
    country: "USA",
    duration: "14m 56s",
    banner: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
    cast: ["Jason Statham", "Tyrese Gibson"],
    trending: false,
    popular: true,
    topRated: false,
    recommended: true,
    isLatest: true,
    tagline: "Drive fast. Die last."
  },
  {
    id: "m19",
    title: "Bioluminescent Depths",
    type: "movie",
    description: "A cinematic documentary exploring rare marine species that illuminate the deepest trenches of the ocean, capturing footage never seen by human eyes before.",
    rating: "9.3",
    year: 2025,
    genres: ["Documentary"],
    language: "English",
    country: "UK",
    duration: "10m 54s",
    banner: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    cast: ["Narrator: David Attenborough"],
    trending: true,
    popular: true,
    topRated: true,
    recommended: true,
    isLatest: true,
    tagline: "Lights in the eternal darkness."
  },
  {
    id: "m20",
    title: "Sintel: Scales of Vengeance",
    type: "movie",
    description: "Continuing her grueling trek across the frozen peaks and scorching deserts, Sintel faces off against a dangerous shaman who claims to know the dragon's location.",
    rating: "8.7",
    year: 2025,
    genres: ["Action", "Drama", "Thriller"],
    language: "English",
    country: "Netherlands",
    duration: "15m 48s",
    banner: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    cast: ["Sintel Hunter", "Shaman of Caves"],
    trending: true,
    popular: true,
    topRated: true,
    recommended: true,
    isLatest: false,
    tagline: "The search ends where the fire begins."
  },

  // ==================== WEB SERIES (s1 to s10) ====================
  {
    id: "s1",
    title: "Digital Anarchy: Hackers",
    type: "series",
    description: "Season 1: A group of rogue cybersecurity specialists execute a high-profile digital heist on a Swiss central bank, only to unleash a lethal AI worm.",
    rating: "9.1",
    year: 2025,
    genres: ["Thriller", "Action"],
    language: "English",
    country: "USA",
    duration: "10 Episodes",
    banner: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    cast: ["Rami Malek", "Christian Slater"],
    trending: true,
    popular: true,
    topRated: true,
    recommended: true,
    isLatest: true
  },
  {
    id: "s2",
    title: "Sacred Underworld Legends",
    type: "series",
    description: "Season 1: Mumbai's criminal empires are thrown into chaos when a mysterious informant gives the police department a 25-day countdown to a national emergency.",
    rating: "8.9",
    year: 2024,
    genres: ["Drama", "Thriller", "Action"],
    language: "Hindi",
    country: "India",
    duration: "8 Episodes",
    banner: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    cast: ["Saif Ali Khan", "Nawazuddin Siddiqui"],
    trending: true,
    popular: true,
    topRated: true,
    recommended: true,
    isLatest: false
  },
  {
    id: "s3",
    title: "Laughter Complex: Season 2",
    type: "series",
    description: "Season 2: Six young professionals face corporate politics, digital dating, and noisy neighbors while sharing a cramped rental apartment in Delhi.",
    rating: "8.6",
    year: 2025,
    genres: ["Comedy", "Romance"],
    language: "Hindi",
    country: "India",
    duration: "12 Episodes",
    banner: "https://images.unsplash.com/photo-1514306191717-452ec28c7814?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1514306191717-452ec28c7814?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    cast: ["Bhuvan Bam", "Srishti Dixit"],
    trending: false,
    popular: true,
    topRated: false,
    recommended: true,
    isLatest: true
  },
  {
    id: "s4",
    title: "Tales of Ancient curses",
    type: "series",
    description: "Season 1: An anthology series investigating paranormal activities in India's most remote abandoned villages, highlighting ancient dark curses.",
    rating: "8.0",
    year: 2024,
    genres: ["Horror", "Drama"],
    language: "English",
    country: "UK",
    duration: "6 Episodes",
    banner: "https://images.unsplash.com/photo-1505635339358-75c102a0a2df?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1505635339358-75c102a0a2df?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    cast: ["Richard Armitage", "Vera Farmiga"],
    trending: false,
    popular: false,
    topRated: false,
    recommended: false,
    isLatest: false
  },
  {
    id: "s5",
    title: "Ancient Pyramids & Mechanics",
    type: "series",
    description: "Season 1: Historians and engineers use high-resolution CGI to show the mechanical engines and gears designed to construct ancient wonders.",
    rating: "8.7",
    year: 2025,
    genres: ["Documentary", "Kids"],
    language: "English",
    country: "USA",
    duration: "8 Episodes",
    banner: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    cast: ["Dr. Sarah Johnson", "Prof. Alan Ross"],
    trending: true,
    popular: true,
    topRated: true,
    recommended: true,
    isLatest: true
  },
  {
    id: "s6",
    title: "The Escape Game",
    type: "series",
    description: "Season 1: A group of international cyber espionage agents are trapped inside an automated smart facility, forced to solve riddles to survive.",
    rating: "8.4",
    year: 2026,
    genres: ["Action", "Thriller"],
    language: "English",
    country: "USA",
    duration: "10 Episodes",
    banner: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    cast: ["John Boyega", "Gemma Chan"],
    trending: true,
    popular: false,
    topRated: false,
    recommended: true,
    isLatest: true
  },
  {
    id: "s7",
    title: "Forest Friends Adventures",
    type: "series",
    description: "Season 1: The cute animals of Bunny forest set up an elaborate detective agency to solve mystery cases, like the missing acorn storage.",
    rating: "8.8",
    year: 2026,
    genres: ["Kids", "Comedy"],
    language: "Hindi",
    country: "India",
    duration: "15 Episodes",
    banner: "https://images.unsplash.com/photo-1500485035595-cbe6f645feb1?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    cast: ["Forest voice cast"],
    trending: true,
    popular: true,
    topRated: true,
    recommended: true,
    isLatest: true
  },
  {
    id: "s8",
    title: "The Joyride Crew",
    type: "series",
    description: "Season 1: Four tech-savvy friends convert a junked garage vehicle into an off-road tracking system, embarking on search missions across raw terrains.",
    rating: "8.1",
    year: 2024,
    genres: ["Action", "Comedy"],
    language: "Hindi",
    country: "India",
    duration: "6 Episodes",
    banner: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    cast: ["Varun Sharma", "Aparshakti Khurana"],
    trending: false,
    popular: true,
    topRated: false,
    recommended: true,
    isLatest: false
  },
  {
    id: "s9",
    title: "Code Red: Reactor Meltdown",
    type: "series",
    description: "Season 1: A tense miniseries tracing the hour-by-hour operations of engineers trying to contain a steam leak in an underground atomic facility.",
    rating: "8.5",
    year: 2024,
    genres: ["Thriller", "Drama"],
    language: "English",
    country: "UK",
    duration: "5 Episodes",
    banner: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
    cast: ["Jared Harris", "Stellan Skarsgård"],
    trending: true,
    popular: false,
    topRated: true,
    recommended: true,
    isLatest: false
  },
  {
    id: "s10",
    title: "High Road: Bullrun racing",
    type: "series",
    description: "Season 1: Documenting the extreme preparation, engineering, and high-speed crashes of drivers participating in the world's most illegal desert race.",
    rating: "8.6",
    year: 2026,
    genres: ["Action", "Documentary"],
    language: "English",
    country: "USA",
    duration: "8 Episodes",
    banner: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1600&q=80",
    thumbnail: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
    cast: ["Top Gear crew", "Pro Racers"],
    trending: true,
    popular: true,
    topRated: true,
    recommended: false,
    isLatest: true
  }
];

// LIVE TV CHANNELS
window.liveChannels = [
  {
    id: "c1",
    name: "Khazana Sports HD",
    logo: "🏆",
    program: "Live Premier League: Man City vs Liverpool",
    nextProgram: "Next: NBA Classics - Bulls vs Lakers (20:30)",
    category: "Sports",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4"
  },
  {
    id: "c2",
    name: "Khazana Cinema",
    logo: "🎬",
    program: "Now Playing: Tears of Steel - Special Edition",
    nextProgram: "Next: Sintel Director's Commentary (21:00)",
    category: "Movies",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4"
  },
  {
    id: "c3",
    name: "King Action TV",
    logo: "💥",
    program: "Now Playing: Shadow Warrior (Rewind)",
    nextProgram: "Next: Cyberpunk Legends (20:00)",
    category: "Movies",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4"
  },
  {
    id: "c4",
    name: "Khazana News Live",
    logo: "📰",
    program: "Prime Time News Bulletin with Rajdeep",
    nextProgram: "Next: Global Business Report (20:00)",
    category: "News",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4"
  },
  {
    id: "c5",
    name: "Kids Zone",
    logo: "🦄",
    program: "Now Playing: Big Buck Bunny and Friends",
    nextProgram: "Next: The Toy Castle Chronicles (19:45)",
    category: "Kids",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    id: "c6",
    name: "Khazana Music Plus",
    logo: "🎵",
    program: "Non-Stop Indie Hits 2026",
    nextProgram: "Next: Late Night Chill Beats (21:00)",
    category: "Music",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4"
  }
];

// SUBSCRIPTION PLANS (Validity-based packages from user request/screenshot)
window.subscriptionPlans = [
  {
    id: "plan-basic",
    name: "Basic Plan",
    validity: "1 Month",
    price: 190,
    resolution: "720p HD",
    screens: 1,
    downloads: "Yes (5 titles)",
    audio: "Stereo 2.0",
    popular: false,
    features: [
      "Access to all Movies and Shows",
      "Watch on Mobile, Tablet or Laptop",
      "720p HD Video Quality",
      "Ad-supported streaming"
    ]
  },
  {
    id: "plan-standard",
    name: "Standard Plan",
    validity: "3 Months",
    price: 1150,
    resolution: "1080p FHD",
    screens: 2,
    downloads: "Yes (30 titles)",
    audio: "Dolby Audio 5.1",
    popular: true,
    features: [
      "Access to all Movies and Shows",
      "Watch on TV, Laptop, Phone & Tablet",
      "1080p Full HD Video Quality",
      "Download & Watch Offline",
      "2 Active Screens simultaneously"
    ]
  },
  {
    id: "plan-pro",
    name: "Pro Plan",
    validity: "6 Months",
    price: 2100,
    resolution: "2K + HDR",
    screens: 3,
    downloads: "Yes (100 titles)",
    audio: "Dolby Digital 5.1",
    popular: false,
    features: [
      "Ad-free premium experience",
      "Watch on TV, Laptop, Phone & Tablet",
      "2K Ultra HD Video Quality",
      "Download & Watch Offline",
      "3 Active Screens simultaneously"
    ]
  },
  {
    id: "plan-premium",
    name: "Premium Plan",
    validity: "12 Months",
    price: 4000,
    resolution: "4K + HDR",
    screens: 4,
    downloads: "Unlimited",
    audio: "Dolby Atmos + Spatial",
    popular: false,
    features: [
      "Ultra HD 4K, HDR10 & Dolby Vision",
      "Ad-free premium experience",
      "Watch on 4 screens simultaneously",
      "Download on up to 10 devices",
      "Immersive Dolby Atmos Sound",
      "First look at new releases"
    ]
  }
];

// FAQS
window.faqs = [
  {
    question: "What is Khazana King OTT?",
    answer: "Khazana King OTT is a premium streaming service that offers a wide variety of award-winning movies, web series, live TV channels, and documentaries on thousands of internet-connected devices. You can watch as much as you want, whenever you want, without a single commercial – all for one low package price!"
  },
  {
    question: "How much does Khazana King OTT cost?",
    answer: "Watch Khazana King OTT on your smartphone, tablet, Smart TV, laptop, or streaming device, all for a single fixed validity fee. Plans range from ₹190 (1 Month) to ₹4000 (12 Months). No extra costs, no contracts. You can easily upgrade or renew your plan at any time."
  },
  {
    question: "Can I cancel my subscription?",
    answer: "Yes, you can easily cancel your auto-renewal or account anytime online. There are no cancellation fees or lock-in contracts – adjust your account status in the User Dashboard with a single click."
  },
  {
    question: "Where can I watch?",
    answer: "Watch anywhere, anytime. Sign in with your Khazana King OTT account to watch instantly on the web from your personal computer or on any internet-connected device, including smart TVs, smartphones, tablets, media players and game consoles."
  },
  {
    question: "Is there content suitable for children?",
    answer: "Yes, the Khazana King OTT Kids experience is included in your membership to give parents control while kids enjoy family-friendly TV shows and movies in their own dedicated space. You can also filter content by the 'Kids' category in our navigation menu."
  }
];

// TESTIMONIALS
window.testimonials = [
  {
    name: "Aarav Mehta",
    role: "Movie Enthusiast",
    rating: 5,
    text: "The streaming quality is absolutely stellar! I subscribed to the Premium plan and the 4K Dolby Atmos audio feels exactly like a theatre experience. Highly recommended!",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=100&h=100&q=80"
  },
  {
    name: "Priya Sharma",
    role: "Binge-Watcher",
    rating: 5,
    text: "I love the Web Series collection. Khazana King has a super clean interface, smooth animations, and the Resume Playback feature is extremely convenient.",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=100&h=100&q=80"
  },
  {
    name: "Vikram Malhotra",
    role: "Tech Professional",
    rating: 4,
    text: "The PWA support is fantastic. I installed the app on my phone directly from the browser. It loads super fast and uses very little data while traveling.",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=100&h=100&q=80"
  }
];

// CATEGORY METADATA
window.categoriesList = [
  { name: "Action", icon: "🔥", gradient: "linear-gradient(135deg, #FF416C, #FF4B2B)" },
  { name: "Drama", icon: "🎭", gradient: "linear-gradient(135deg, #8A2387, #E94057)" },
  { name: "Thriller", icon: "👁️", gradient: "linear-gradient(135deg, #111111, #461b1b)" },
  { name: "Comedy", icon: "😄", gradient: "linear-gradient(135deg, #F9D423, #FF4E50)" },
  { name: "Horror", icon: "🧟", gradient: "linear-gradient(135deg, #2c3e50, #000000)" },
  { name: "Romance", icon: "💖", gradient: "linear-gradient(135deg, #ff9a9e, #fecfef)" },
  { name: "Documentary", icon: "🌍", gradient: "linear-gradient(135deg, #2b5876, #4e4376)" },
  { name: "Kids", icon: "🎈", gradient: "linear-gradient(135deg, #00c6ff, #0072ff)" }
];
